name = "anon-bbs"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "anon-bbs"
database_id = "6bc84fa2-3d16-4781-a035-6beefb000183"

[vars]
ALLOWED_ORIGIN = "https://tigeregg80.github.io"
